version: '3.7'

services: 
  web:
    build: ./laundrybasket
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - ./laundrybasket/:/usr/src/laundrybasket/
    ports: 
      - 8000:8000
    env_file: 
      - ./.env.dev
  
  db:
    image: postgres
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
      
volumes:
  postgres_data: